* Exercise 1.6.
#+BEGIN_QUOTE
Alyssa P. Hacker doesn't see why if needs to be provided as a special form. ``Why can't I just define it as an ordinary procedure in terms of cond?'' she asks. Alyssa's friend Eva Lu Ator claims this can indeed be done, and she defines a new version of if:
#+END_QUOTE

#+BEGIN_SRC scheme 
(define (new-if predicate then-clause else-clause)
  (cond (predicate then-clause)
        (else else-clause)))
#+END_SRC

#+BEGIN_QUOTE
Eva demonstrates the program for Alyssa:
#+END_QUOTE

#+BEGIN_EXAMPLE
(new-if (= 2 3) 0 5)
5

(new-if (= 1 1) 0 5)
0
#+END_EXAMPLE

#+BEGIN_QUOTE
Delighted, Alyssa uses new-if to rewrite the square-root program:
#+END_QUOTE

#+BEGIN_SRC scheme 
(define (sqrt-iter guess x)
  (new-if (good-enough? guess x)
          guess
          (sqrt-iter (improve guess x)
                     x)))
#+END_SRC

#+BEGIN_QUOTE
What happens when Alyssa attempts to use this to compute square roots? Explain.
#+END_QUOTE

* Analysis
Special forms do not follow the normal (general) evaluation rule. /if/ is a special form. If the predicate is true, the alternative to the consequent is _not_ evaluated.

/cond/ is a normal form (following the general evaluation rule), in the sense that _all_ predicates are evaluated even if only the consequent corresponding to the first true predicate is returned.

Evidence:
#+BEGIN_SRC scheme
  (cond ((= 2 2)
         7)
        (else (8))
  ;Error

  (if (= 2 2)
       7
       (8))
  ;Value: 7
#+END_SRC


#+BEGIN_SRC scheme
  ;; The original procedure
  (define (sqrt-iter guess x)
    (if (good-enough? guess x)          ; if preditcate function 
        guess                           ; guess
        (sqrt-iter (improve guess x)    ; else ... 
                   x)))
  ;; The modified procedure
  (define (sqrt-iter guess x)
    (new-if (good-enough? guess x)
            guess
            (sqrt-iter (improve guess x)
                       x)))
  ;; The modificator
  (define (new-if predicate then-clause else-clause)
    (cond (predicate then-clause) ; this will evaluate
          (else else-clause)))    ; and this
#+END_SRC

The /good-enough?/ procedure will return true if the square of /guess/ deviates from x by less than 0.001. In the case of /if/ this will result in /guess/ being returned to the recurring /sqrt-iter/, otherwise one additional recursion. In the case of /new-if/ a #t from the /good-enough?/ procedure will return /guess/ to the recurring sqrt-iter, but it will also evaluate the else-clause, resulting in an endless recursion, since...



Guessing:
The else case in the cond procedure will evaluate something at some point wich will return an error.

The two: then-clause and else-clause:
the then-clause is a procedure while the else clause is the number which square root is beinc calculated.

(define (good-enough? guess x)
  (< (abs (- (square guess) x)) 0.001))



good-enough? is the first case in the cond. It takes guess and x as formal parameters. 




* Conclusion
As explained above, /cond/ evaluates all caluses. The implication for the sqrt procedure in this respect is that ... 
